var nolan = [
   {
      "movie":"Interstellar",
      "data":{
         "rating":{
            "text":"8.6"
         },
         "votes":{
            "text":"884007"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1._SX90_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"169"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2014"
         }
      }
   },
   {
      "movie":"The Dark Knight Rises",
      "data":{
         "rating":{
            "text":"8.5"
         },
         "votes":{
            "text":"1111971"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"164"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2012"
         }
      }
   },
   {
      "movie":"Inception",
      "data":{
         "rating":{
            "text":"8.8"
         },
         "votes":{
            "text":"1424645"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"148"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2010"
         }
      }
   },
   {
      "movie":"The Dark Knight",
      "data":{
         "rating":{
            "text":"9.0"
         },
         "votes":{
            "text":"1630017"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"152"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2008"
         }
      }
   },
   {
      "movie":"The Prestige",
      "data":{
         "rating":{
            "text":"8.5"
         },
         "votes":{
            "text":"818152"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"130"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2006"
         }
      }
   },
   {
      "movie":"Batman Begins",
      "data":{
         "rating":{
            "text":"8.3"
         },
         "votes":{
            "text":"952174"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNTM3OTc0MzM2OV5BMl5BanBnXkFtZTYwNzUwMTI3._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"140"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2005"
         }
      }
   },
   {
      "movie":"Insomnia",
      "data":{
         "rating":{
            "text":"7.2"
         },
         "votes":{
            "text":"214426"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTM5Nzk2NDY3MF5BMl5BanBnXkFtZTgwMzI5MDgxMTE@._V1._SX93_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"118"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2002"
         }
      }
   },
   {
      "movie":"Memento",
      "data":{
         "rating":{
            "text":"8.5"
         },
         "votes":{
            "text":"824240"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTc4MjUxNDAwN15BMl5BanBnXkFtZTcwMDMwNDg3OA@@._V1._SX100_SY133_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"113"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"2000"
         }
      }
   },
   {
      "movie":"Following",
      "data":{
         "rating":{
            "text":"7.6"
         },
         "votes":{
            "text":"64320"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjExMzE1NzA5N15BMl5BanBnXkFtZTYwNzA5ODI5._V1._SX99_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"69"
         },
         "director":{
            "text":{
               "@id":"0634240",
               "name":"Christopher Nolan"
            }
         },
         "year":{
            "text":"1998"
         }
      }
   },
];