var oscars2016 = [
    {
        "movie":"The Big Short",
        "data":{
            "votes":{
                "text":142852
            },
            "rating":{
                "text":7.8
            },
            "runtimes":{
                "text":130
            },
            "year":{
                "text":2015
            },
            "director":{
                "person":{
                    "name":"Adam McKay"
                }
            }, 
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMjM2MTQ2MzcxOF5BMl5BanBnXkFtZTgwNzE4NTUyNzE@._V1._SX90_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":70259870
            },
            "grossWorld":{
                "text":132950761
            },
            "rt":{
                "text":88
            },
            "rtAudience":{
                "text":88
            }
        }
    },

    {
        "movie":"Bridge of Spies",
        "data":{
            "votes":{
                "text":"152942"
            },
            "rating":{
                "text":"7.6"
            },
            "runtimes":{
                "text":"142"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"Steven Spielberg"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMjIxOTI0MjU5NV5BMl5BanBnXkFtZTgwNzM4OTk4NTE@._V1._SX94_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":72313754
            },
            "grossWorld":{
                "text":165478348
            },
            "rt":{
                "text":91
            },
            "rtAudience":{
                "text":87
            }
        }
    },

    {
        "movie":"Brooklyn",
        "data":{
            "votes":{
                "text":"59483"
            },
            "rating":{
                "text":"7.5"
            },
            "runtimes":{
                "text":"111"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"John Crowley"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMzE4MDk5NzEyOV5BMl5BanBnXkFtZTgwNDM4NDA3NjE@._V1._SX94_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":38240418
            },
            "grossWorld":{
                "text":61993816
            },
            "rt":{
                "text":97
            },
            "rtAudience":{
                "text":88
            }
        }
    },

    {
        "movie":"Mad Max: Fury Road",
        "data":{
            "votes":{
                "text":"507862"
            },
            "rating":{
                "text":"8.1"
            },
            "runtimes":{
                "text":"120"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"George Miller"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMTUyMTE0ODcxNF5BMl5BanBnXkFtZTgwODE4NDQzNTE@._V1._SX96_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":153636354
            },
            "grossWorld":{
                "text":378436354
            },
            "rt":{
                "text":97
            },
            "rtAudience":{
                "text":86
            }
        }
    },

    {
        "movie":"The Martian",
        "data":{
            "votes":{
                "text":"414803"
            },
            "rating":{
                "text":"8.1"
            },
            "runtimes":{
                "text":"144"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"Ridley Scott"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1._SX95_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":228433663
            },
            "grossWorld":{
                "text":630161890
            },
            "rt":{
                "text":92
            },
            "rtAudience":{
                "text":92
            }
        }
    },

    {
        "movie":"The Revenant",
        "data":{
            "votes":{
                "text":"333115"
            },
            "rating":{
                "text":"8.1"
            },
            "runtimes":{
                "text":"156"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"Alejandro G. I\u00f1\u00e1rritu"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMjU4NDExNDM1NF5BMl5BanBnXkFtZTgwMDIyMTgxNzE@._V1._SX94_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":183407381
            },
            "grossWorld":{
                "text":522837095
            },
            "rt":{
                "text":82
            },
            "rtAudience":{
                "text":85
            }
        }
    },

    {
        "movie":"Room",
        "data":{
            "votes":{
                "text":"124259"
            },
            "rating":{
                "text":"8.3"
            },
            "runtimes":{
                "text":"118"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"Lenny Abrahamson"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1._SX94_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":14676564
            },
            "grossWorld":{
                "text":35400668
            },
            "rt":{
                "text":93
            },
            "rtAudience":{
                "text":94
            }
        }
    },

    {
        "movie":"Spotlight",
        "data":{
            "votes":{
                "text":"151647"
            },
            "rating":{
                "text":"8.1"
            },
            "runtimes":{
                "text":"128"
            },
            "year":{
                "text":"2015"
            },
            "director":{
                "person":{
                    "name":"Tom McCarthy"
                }
            },
            "cover":{
                "url":"http://ia.media-imdb.com/images/M/MV5BMjIyOTM5OTIzNV5BMl5BanBnXkFtZTgwMDkzODE2NjE@._V1._SX95_SY140_.jpg",
                "w":89,
                "h":140
            },
            "grossDom":{
                "text":44871255
            },
            "grossWorld":{
                "text":88161952
            },
            "rt":{
                "text":96
            },
            "rtAudience":{
                "text":93
            }
        }
    }
];

