var oscars2013 = [
   {
      "movie":"Silver Linings Playbook",
      "data":{
         "grossDom":{
            "text":132092958
         },
         "rating":{
            "text":"7.8"
         },
         "votes":{
            "text":"521507"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTM2MTI5NzA3MF5BMl5BanBnXkFtZTcwODExNTc0OA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"122"
         },
         "director":{
            "text":{
               "@id":"0751102",
               "name":"David O. Russell"
            }
         },
         "grossWorld":{
            "text":236412453
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":92
         }
      }
   },
   {
      "movie":"Amour",
      "data":{
         "grossDom":{
            "text":6739492
         },
         "rating":{
            "text":"7.9"
         },
         "votes":{
            "text":"68805"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTk1NTc3NDc4MF5BMl5BanBnXkFtZTcwNjYwNDk0OA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"127"
         },
         "director":{
            "text":{
               "@id":"0359734",
               "name":"Michael Haneke"
            }
         },
         "grossWorld":{
            "text":19839492
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":93
         }
      }
   },
   {
      "movie":"Django Unchained",
      "data":{
         "grossDom":{
            "text":162805434
         },
         "rating":{
            "text":"8.5"
         },
         "votes":{
            "text":"922852"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjIyNTQ5NjQ1OV5BMl5BanBnXkFtZTcwODg1MDU4OA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"165"
         },
         "director":{
            "text":{
               "@id":"0000233",
               "name":"Quentin Tarantino"
            }
         },
         "grossWorld":{
            "text":425368238
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":88
         }
      }
   },
   {
      "movie":"Zero Dark Thirty",
      "data":{
         "grossDom":{
            "text":95720716
         },
         "rating":{
            "text":"7.4"
         },
         "votes":{
            "text":"212345"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTQ4OTUyNzcwN15BMl5BanBnXkFtZTcwMTQ1NDE3OA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"157"
         },
         "director":{
            "text":{
               "@id":"0000941",
               "name":"Kathryn Bigelow"
            }
         },
         "grossWorld":{
            "text":132820716
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":92
         }
      }
   },
   {
      "movie":"Lincoln",
      "data":{
         "grossDom":{
            "text":182207973
         },
         "rating":{
            "text":"7.4"
         },
         "votes":{
            "text":"193718"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTQzNzczMDUyNV5BMl5BanBnXkFtZTcwNjM2ODEzOA@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"150"
         },
         "director":{
            "text":{
               "@id":"0000229",
               "name":"Steven Spielberg"
            }
         },
         "grossWorld":{
            "text":275293450
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":90
         }
      }
   },
   {
      "movie":"Life of Pi",
      "data":{
         "grossDom":{
            "text":124987023
         },
         "rating":{
            "text":"8.0"
         },
         "votes":{
            "text":"426978"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNTg2OTY2ODg5OF5BMl5BanBnXkFtZTcwODM5MTYxOA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"127"
         },
         "director":{
            "text":{
               "@id":"0000487",
               "name":"Ang Lee"
            }
         },
         "grossWorld":{
            "text":609016565
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":87
         }
      }
   },
   {
      "movie":"Argo",
      "data":{
         "grossDom":{
            "text":136025503
         },
         "rating":{
            "text":"7.8"
         },
         "votes":{
            "text":"441939"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTc3MjI0MjM0NF5BMl5BanBnXkFtZTcwMTYxMTQ1OA@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"120"
         },
         "director":{
            "text":{
               "@id":"0000255",
               "name":"Ben Affleck"
            }
         },
         "grossWorld":{
            "text":232325503
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":96
         }
      }
   },
   {
      "movie":"Les Miserables",
      "data":{
         "grossDom":{
            "text":148809770
         },
         "rating":{
            "text":"7.6"
         },
         "votes":{
            "text":"238996"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTQ4NDI3NDg4M15BMl5BanBnXkFtZTcwMjY5OTI1OA@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"158"
         },
         "director":{
            "text":{
               "@id":"0393799",
               "name":"Tom Hooper"
            }
         },
         "grossWorld":{
            "text":441809770
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":69
         }
      }
   },
   {
      "movie":"Beasts of the Southern Wild",
      "data":{
         "grossDom":{
            "text":12795746
         },
         "rating":{
            "text":"7.3"
         },
         "votes":{
            "text":"69378"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTgxNDM5MDM1Ml5BMl5BanBnXkFtZTcwOTYwNzQ3Nw@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"93"
         },
         "director":{
            "text":{
               "@id":"1022455",
               "name":"Benh Zeitlin"
            }
         },
         "grossWorld":{
            "text":21107746
         },
         "year":{
            "text":"2012"
         },
         "rt":{
            "text":86
         }
      }
   }
]