var oscars2015 = [
   {
      "movie":"Whiplash",
      "data":{
         "grossDom":{
            "text":13092000
         },
         "rating":{
            "text":"8.5"
         },
         "votes":{
            "text":"373225"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTU4OTQ3MDUyMV5BMl5BanBnXkFtZTgwOTA2MjU0MjE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"107"
         },
         "director":{
            "text":{
               "@id":"3227090",
               "name":"Damien Chazelle"
            }
         },
         "grossWorld":{
            "text":48982041
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":94
         }
      }
   },
   {
      "movie":"American Sniper",
      "data":{
         "grossDom":{
            "text":350126372
         },
         "rating":{
            "text":"7.3"
         },
         "votes":{
            "text":"312275"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTkxNzI3ODI4Nl5BMl5BanBnXkFtZTgwMjkwMjY4MjE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"133"
         },
         "director":{
            "text":{
               "@id":"0000142",
               "name":"Clint Eastwood"
            }
         },
         "grossWorld":{
            "text":547426372
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":72
         }
      }
   },
   {
      "movie":"Birdman or (The Unexpected Virtue of Ignorance)",
      "data":{
         "grossDom":{
            "text":42340598
         },
         "rating":{
            "text":"7.8"
         },
         "votes":{
            "text":"377568"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BODAzNDMxMzAxOV5BMl5BanBnXkFtZTgwMDMxMjA4MjE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"119"
         },
         "director":{
            "text":{
               "@id":"0327944",
               "name":"Alejandro G. I\u00f1\u00e1rritu"
            }
         },
         "grossWorld":{
            "text":103215094
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":91
         }
      }
   },
   {
      "movie":"The Grand Budapest Hotel",
      "data":{
         "grossDom":{
            "text":59301324
         },
         "rating":{
            "text":"8.1"
         },
         "votes":{
            "text":"453520"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"99"
         },
         "director":{
            "text":{
               "@id":"0027572",
               "name":"Wes Anderson"
            }
         },
         "grossWorld":{
            "text":174801324
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":92
         }
      }
   },
   {
      "movie":"The Imitation Game",
      "data":{
         "grossDom":{
            "text":91125683
         },
         "rating":{
            "text":"8.1"
         },
         "votes":{
            "text":"439078"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNDkwNTEyMzkzNl5BMl5BanBnXkFtZTgwNTAwNzk3MjE@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"114"
         },
         "director":{
            "text":{
               "@id":"0878763",
               "name":"Morten Tyldum"
            }
         },
         "grossWorld":{
            "text":233555708
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":90
         }
      }
   },
   {
      "movie":"Selma",
      "data":{
         "grossDom":{
            "text":52076908
         },
         "rating":{
            "text":"7.5"
         },
         "votes":{
            "text":"58496"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BODMxNjAwODA2Ml5BMl5BanBnXkFtZTgwMzc0NjgzMzE@._V1._SX90_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"128"
         },
         "director":{
            "text":{
               "@id":"1148550",
               "name":"Ava DuVernay"
            }
         },
         "grossWorld":{
            "text":66787908
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":99
         }
      }
   },
   {
      "movie":"The Theory of Everything",
      "data":{
         "grossDom":{
            "text":35893537
         },
         "rating":{
            "text":"7.7"
         },
         "votes":{
            "text":"252314"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTAwMTU4MDA3NDNeQTJeQWpwZ15BbWU4MDk4NTMxNTIx._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"123"
         },
         "director":{
            "text":{
               "@id":"1016428",
               "name":"James Marsh"
            }
         },
         "grossWorld":{
            "text":123726688
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":79
         }
      }
   },
   {
      "movie":"Boyhood",
      "data":{
         "grossDom":{
            "text":25352281
         },
         "rating":{
            "text":"8.0"
         },
         "votes":{
            "text":"257898"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTYzNDc2MDc0N15BMl5BanBnXkFtZTgwOTcwMDQ5MTE@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"165"
         },
         "director":{
            "text":{
               "@id":"0000500",
               "name":"Richard Linklater"
            }
         },
         "grossWorld":{
            "text":44495281
         },
         "year":{
            "text":"2014"
         },
         "rt":{
            "text":98
         }
      }
   }
];