var oscars2014 = [
   {
      "movie":"Philomena",
      "data":{
         "grossDom":{
            "text":37709979
         },
         "rating":{
            "text":"7.6"
         },
         "votes":{
            "text":"74181"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjA5ODgyNzcxMV5BMl5BanBnXkFtZTgwMzkzOTYzMDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"98"
         },
         "director":{
            "text":{
               "@id":"0001241",
               "name":"Stephen Frears"
            }
         },
         "grossWorld":{
            "text":100129872
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":92
         },
         "rtAudience":{
            "text":89
         }
      }
   },
   {
      "movie":"Nebraska",
      "data":{
         "grossDom":{
            "text":17654912
         },
         "rating":{
            "text":"7.8"
         },
         "votes":{
            "text":"89000"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTU2Mjk2NDkyMl5BMl5BanBnXkFtZTgwNTk0NzcyMDE@._V1._SX90_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"115"
         },
         "director":{
            "text":{
               "@id":"0668247",
               "name":"Alexander Payne"
            }
         },
         "grossWorld":{
            "text":27682872
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":91
         },
         "rtAudience":{
            "text":83
         }
      }
   },
   {
      "movie":"Captain Phillips",
      "data":{
         "grossDom":{
            "text":107100855
         },
         "rating":{
            "text":"7.9"
         },
         "votes":{
            "text":"316053"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTQzNzExMDg3Ml5BMl5BanBnXkFtZTgwODU1NzEzMDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"134"
         },
         "director":{
            "text":{
               "@id":"0339030",
               "name":"Paul Greengrass"
            }
         },
         "grossWorld":{
            "text":218791811
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":93
         },
         "rtAudience":{
            "text":89
         }
      }
   },
   {
      "movie":"The Wolf of Wall Street",
      "data":{
         "grossDom":{
            "text":116900694
         },
         "rating":{
            "text":"8.2"
         },
         "votes":{
            "text":"747076"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"180"
         },
         "director":{
            "text":{
               "@id":"0000217",
               "name":"Martin Scorsese"
            }
         },
         "grossWorld":{
            "text":392000694
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":77
         },
         "rtAudience":{
            "text":82
         }
      }
   },
   {
      "movie":"Twelve Years a Slave",
      "data":{
         "grossDom":{
            "text":56671993
         },
         "rating":{
            "text":"8.1"
         },
         "votes":{
            "text":"421921"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"134"
         },
         "director":{
            "text":{
               "@id":"2588606",
               "name":"Steve McQueen"
            }
         },
         "grossWorld":{
            "text":187733202
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":96
         },
         "rtAudience":{
            "text":90
         }
      }
   },
   {
      "movie":"Her",
      "data":{
         "grossDom":{
            "text":25568251
         },
         "rating":{
            "text":"8.0"
         },
         "votes":{
            "text":"341875"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"126"
         },
         "director":{
            "text":{
               "@id":"0005069",
               "name":"Spike Jonze"
            }
         },
         "grossWorld":{
            "text":47351251
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":94
         },
         "rtAudience":{
            "text":82
         }
      }
   },
   {
      "movie":"Gravity",
      "data":{
         "grossDom":{
            "text":274092705
         },
         "rating":{
            "text":"7.8"
         },
         "votes":{
            "text":"567599"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"91"
         },
         "director":{
            "text":{
               "@id":"0190859",
               "name":"Alfonso Cuar\u00f3n"
            }
         },
         "grossWorld":{
            "text":723192705
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":96
         },
         "rtAudience":{
            "text":80
         }
      }
   },
   {
      "movie":"American Hustle",
      "data":{
         "grossDom":{
            "text":150117807
         },
         "rating":{
            "text":"7.3"
         },
         "votes":{
            "text":"351256"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNjkxMTc0MDc4N15BMl5BanBnXkFtZTgwODUyNTI1MDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"138"
         },
         "director":{
            "text":{
               "@id":"0751102",
               "name":"David O. Russell"
            }
         },
         "grossWorld":{
            "text":251171807
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":93
         },
         "rtAudience":{
            "text":74
         }
      }
   },
   {
      "movie":"Dallas Buyers Club",
      "data":{
         "grossDom":{
            "text":27298285
         },
         "rating":{
            "text":"8.0"
         },
         "votes":{
            "text":"316842"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTYwMTA4MzgyNF5BMl5BanBnXkFtZTgwMjEyMjE0MDE@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"117"
         },
         "director":{
            "text":{
               "@id":"0885249",
               "name":"Jean-Marc Vall\u00e9e"
            }
         },
         "grossWorld":{
            "text":55198285
         },
         "year":{
            "text":"2013"
         },
         "rt":{
            "text":94
         },
         "rtAudience":{
            "text":91
         }
      }
   }
];