var oscars2012 = [
   {
      "movie":"The Descendants",
      "data":{
         "grossDom":{
            "text":82584160
         },
         "rating":{
            "text":"7.3"
         },
         "votes":{
            "text":"202700"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjAyNTA1MTcyN15BMl5BanBnXkFtZTcwNjEyODczNQ@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"115"
         },
         "director":{
            "text":{
               "name":"Alexander Payne"
            }
         },
         "grossWorld":{
            "text":177243185
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":89
         },
         "rtAudience":{
            "text":79
         }
      }
   },
   {
      "movie":"The Artist",
      "data":{
         "grossDom":{
            "text":44671682
         },
         "rating":{
            "text":"8.0"
         },
         "votes":{
            "text":"186781"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMzk0NzQxMTM0OV5BMl5BanBnXkFtZTcwMzU4MDYyNQ@@._V1._SX100_SY133_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"100"
         },
         "director":{
            "text":{
               "name":"Michel Hazanavicius"
            }
         },
         "grossWorld":{
            "text":133432856
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":97
         },
         "rtAudience":{
            "text":87
         }
      }
   },
   {
      "movie":"Extremely Loud & Incredibly Close",
      "data":{
         "grossDom":{
            "text":31847881
         },
         "rating":{
            "text":"6.9"
         },
         "votes":{
            "text":"79546"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTUxNzYwMTE3NV5BMl5BanBnXkFtZTcwMDY2NzU4Ng@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"129"
         },
         "director":{
            "text":{
               "name":"Stephen Daldry"
            }
         },
         "grossWorld":{
            "text":55247881
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":46
         },
         "rtAudience":{
            "text":61
         }
      }
   },
   {
      "movie":"Moneyball",
      "data":{
         "grossDom":{
            "text":75605492
         },
         "rating":{
            "text":"7.6"
         },
         "votes":{
            "text":"278563"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjAxOTU3Mzc1M15BMl5BanBnXkFtZTcwMzk1ODUzNg@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"133"
         },
         "director":{
            "text":{
               "name":"Bennett Miller"
            }
         },
         "grossWorld":{
            "text":110206216
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":94
         },
         "rtAudience":{
            "text":86
         }
      }
   },
   {
      "movie":"Midnight in Paris",
      "data":{
         "grossDom":{
            "text":56817045
         },
         "rating":{
            "text":"7.7"
         },
         "votes":{
            "text":"294341"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTM4NjY1MDQwMl5BMl5BanBnXkFtZTcwNTI3Njg3NA@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"94"
        },
         "director":{
            "text":{
               "name":"Woody Allen"
            }
         },
         "grossWorld":{
            "text":151119219
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":93
         },
         "rtAudience":{
            "text":83
         }
      }
   },
   {
      "movie":"War Horse",
      "data":{
         "grossDom":{
            "text":79884879
         },
         "rating":{
            "text":"7.2"
         },
         "votes":{
            "text":"114024"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjExNzkxOTYyNl5BMl5BanBnXkFtZTcwODA0MjU4Ng@@._V1._SX95_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"146"
         },
         "director":{
            "text":{
               "name":"Steven Spielberg"
            }
         },
         "grossWorld":{
            "text":177584879
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":76
         },
         "rtAudience":{
            "text":74
         }
      }
   },
   {
      "movie":"The Tree of Life",
      "data":{
         "grossDom":{
            "text":13303319
         },
         "rating":{
            "text":"6.7"
         },
         "votes":{
            "text":"133688"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BNTgyNTQzMDEwNV5BMl5BanBnXkFtZTcwMTQxNjI4NA@@._V1._SX89_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"139"
         },
         "director":{
            "text":{
               "name":"Terrence Malick"
            }
         },
         "grossWorld":{
            "text":54303319
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":84
         },
         "rtAudience":{
            "text":60
         }
      }
   },
   {
      "movie":"Hugo",
      "data":{
         "grossDom":{
            "text":73864507
         },
         "rating":{
            "text":"7.6"
         },
         "votes":{
            "text":"240892"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMjAzNzk5MzgyNF5BMl5BanBnXkFtZTcwOTE4NDU5Ng@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"126"
         },
         "director":{
            "text":{
               "name":"Martin Scorsese"
            }
         },
         "grossWorld":{
            "text":185770160
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":94
         },
         "rtAudience":{
            "text":78
         }
      }
   },
   {
      "movie":"The Help",
      "data":{
         "grossDom":{
            "text":169708112
         },
         "rating":{
            "text":"8.1"
         },
         "votes":{
            "text":"310517"
         },
         "cover":{
            "url":"http://ia.media-imdb.com/images/M/MV5BMTM5OTMyMjIxOV5BMl5BanBnXkFtZTcwNzU4MjIwNQ@@._V1._SX94_SY140_.jpg",
            "h":140,
            "w":95
         },
         "runtimes":{
            "text":"146"
         },
         "director":{
            "text":{
               "name":"Tate Taylor"
            }
         },
         "grossWorld":{
            "text":216639112
         },
         "year":{
            "text":"2011"
         },
         "rt":{
            "text":75
         },
         "rtAudience":{
            "text":89
         }
      }
   }
];